export const verbs = [
  {
    first: "arise",
    second: "arose",
    third: "arisen",
    geo: "წამოწევა",
  },
  {
    first: "awake",
    second: "awoke",
    third: "awoken",
    geo: "გამოღვიძება",
  },
  {
    first: "be",
    second: "was",
    third: "been",
    geo: "ყოფნა",
  },
  {
    first: "bear",
    second: "bore",
    third: "born",
    geo: "დაბადება",
  },
  {
    first: "beat",
    second: "beat",
    third: "beaten",
    geo: "ცემა",
  },
  {
    first: "become",
    second: "became",
    third: "become",
    geo: "გადაქცევა",
  },
  {
    first: "beget",
    second: "begot",
    third: "begotten",
    geo: "დაბადება",
  },
  {
    first: "begin",
    second: "began",
    third: "begun",
    geo: "დაწყება",
  },
  {
    first: "bend",
    second: "bent",
    third: "bent",
    geo: "მოხრა",
  },
  {
    first: "beseech",
    second: "besought",
    third: "besought",
    geo: "ვედრება",
  },
  {
    first: "bet",
    second: "bet",
    third: "bet",
    geo: "დანაძლევება",
  },
  {
    first: "bid",
    second: "bade",
    third: "bidden",
    geo: "შეთავაზება ფასის",
  },
  {
    first: "bide",
    second: "bade",
    third: "bided",
    geo: "არსებობა",
  },
  {
    first: "bind",
    second: "bound",
    third: "bound",
    geo: "დაკავშირება",
  },
  {
    first: "bite",
    second: "bit",
    third: "bitten",
    geo: "კბე­ნა",
  },
  {
    first: "bleed",
    second: "bled",
    third: "bled",
    geo: "სისხლდენა",
  },
  {
    first: "blow",
    second: "blew",
    third: "blown",
    geo: "დაბერვა",
  },
  {
    first: "break",
    second: "broke",
    third: "broken",
    geo: "გატეხვა",
  },
  {
    first: "breed",
    second: "bred",
    third: "bred",
    geo: "გამრავლება",
  },
  {
    first: "bring",
    second: "brought",
    third: "brought",
    geo: "მოტანა",
  },
  {
    first: "broadcast",
    second: "broadcast",
    third: "broadcast",
    geo: "ტრანსლაცია",
  },
  {
    first: "build",
    second: "built",
    third: "built",
    geo: "აშენება",
  },
  {
    first: "burn",
    second: "burnt",
    third: "burnt",
    geo: "დაწვა",
  },
  {
    first: "burst",
    second: "burst",
    third: "burst",
    geo: "აფეთ­ქე­ბა",
  },
  {
    first: "buy",
    second: "bought",
    third: "bought",
    geo: "შესყიდვა",
  },
  {
    first: "can",
    second: "could",
    third: "could",
    geo: "შეძლება",
  },
  {
    first: "cast",
    second: "cast",
    third: "cast",
    geo: "ტყორცნა",
  },
  {
    first: "catch",
    second: "caught",
    third: "caught",
    geo: "დაჭერა",
  },
  {
    first: "choose",
    second: "chose",
    third: "chosen",
    geo: "არჩევა",
  },
  {
    first: "cleave",
    second: "cleft",
    third: "cleft",
    geo: "გაპობა",
  },
  {
    first: "cling",
    second: "clung",
    third: "clung",
    geo: "მიწებება",
  },
  {
    first: "come",
    second: "came",
    third: "come",
    geo: "მოსვლა",
  },
  {
    first: "cost",
    second: "cost",
    third: "cost",
    geo: "ღირებულება",
  },
  {
    first: "creep",
    second: "crept",
    third: "crept",
    geo: "ცოცვა",
  },
  {
    first: "cut",
    second: "cut",
    third: "cut",
    geo: "გაჭრა",
  },
  {
    first: "deal",
    second: "dealt",
    third: "dealt",
    geo: "გარიგება",
  },
  {
    first: "dig",
    second: "dug",
    third: "dug",
    geo: "გათხრა",
  },
  {
    first: "do",
    second: "did",
    third: "done",
    geo: "გაკეთება",
  },
  {
    first: "draw",
    second: "drew",
    third: "drawn",
    geo: "გამოწევა",
  },
  {
    first: "drink",
    second: "drank",
    third: "drunk",
    geo: "დალევა",
  },
  {
    first: "drive ",
    second: "drove",
    third: "driven",
    geo: "ავტომობილის მართვა",
  },
  {
    first: "dwell",
    second: "dwelt",
    third: "dwelt",
    geo: "ცხოვრება",
  },
  {
    first: "eat",
    second: "ate",
    third: "eaten",
    geo: "ჭამა",
  },
  {
    first: "fall",
    second: "fell",
    third: "fallen",
    geo: "დაცემა",
  },
  {
    first: "feed",
    second: "fed",
    third: "fed",
    geo: "გამოკვება",
  },
  {
    first: "feel",
    second: "felt",
    third: "felt",
    geo: "შეგრძნება",
  },
  {
    first: "fight",
    second: "fought",
    third: "fought",
    geo: "ბრძოლა",
  },
  {
    first: "find",
    second: "found",
    third: "found",
    geo: "პოვნა",
  },
  {
    first: "flee",
    second: "fled",
    third: "fled",
    geo: "გაქცევა",
  },
  {
    first: "fling",
    second: "flung",
    third: "flung",
    geo: "ტყორცნა",
  },
  {
    first: "fly",
    second: "flew",
    third: "flown",
    geo: "ფრენა",
  },
  {
    first: "forbid",
    second: "forbade",
    third: "forbidden",
    geo: "აკრძალვა",
  },
  {
    first: "forget",
    second: "forgot",
    third: "forgotten",
    geo: "დავიწყება",
  },
  {
    first: "forsake",
    second: "forsook",
    third: "forsaken",
    geo: "მიტოვება",
  },
  {
    first: "freeze",
    second: "froze",
    third: "frozen",
    geo: "გაყინვა",
  },
  {
    first: "get",
    second: "got",
    third: "got",
    geo: "მიღება",
  },
  {
    first: "give",
    second: "gave",
    third: "given",
    geo: "მიცემა",
  },
  {
    first: "go",
    second: "went",
    third: "gone",
    geo: "წასვლა",
  },
  {
    first: "grind",
    second: "ground",
    third: "ground",
    geo: "დაფქვა",
  },
  {
    first: "grow",
    second: "grew",
    third: "grown",
    geo: "გაზრდა",
  },
  {
    first: "hang",
    second: "hung",
    third: "hung",
    geo: "დაკიდება",
  },
  {
    first: "have",
    second: "had",
    third: "had",
    geo: "ქონა, ყოლა",
  },
  {
    first: "hear",
    second: "heard",
    third: "heard",
    geo: "გაგება",
  },
  {
    first: "hide",
    second: "hid",
    third: "hidden",
    geo: "დამალვა",
  },
  {
    first: "hit",
    second: "hit",
    third: "hit",
    geo: "დარტყმა",
  },
  {
    first: "hold",
    second: "held",
    third: "held",
    geo: "დაჭერა",
  },
  {
    first: "hurt",
    second: "hurt",
    third: "hurt",
    geo: "დაზიანება",
  },
  {
    first: "keep",
    second: "kept",
    third: "kept",
    geo: "შენახვა",
  },
  {
    first: "kneel",
    second: "knelt",
    third: "knelt",
    geo: "მუხლის მოყრა",
  },
  {
    first: "know",
    second: "knew",
    third: "known",
    geo: "ცოდნა",
  },
  {
    first: "lead",
    second: "led",
    third: "led",
    geo: "წაყვანა",
  },
  {
    first: "learn",
    second: "learnt",
    third: "learnt",
    geo: "შესწავლა",
  },
  {
    first: "leave",
    second: "left",
    third: "left",
    geo: "დატოვება",
  },
  {
    first: "lend",
    second: "lent",
    third: "lent",
    geo: "თხოვება",
  },
  {
    first: "let",
    second: "let",
    third: "let",
    geo: "ნების დართვა",
  },
  {
    first: "light",
    second: "lit",
    third: "lit",
    geo: "ანთება",
  },
  {
    first: "lose",
    second: "lost",
    third: "lost",
    geo: "დაკარგვა",
  },
  {
    first: "make",
    second: "made",
    third: "made",
    geo: "გაკეთება",
  },
  {
    first: "mean",
    second: "meant",
    third: "meant",
    geo: "მნიშვნელობის ქონა",
  },
  {
    first: "meet",
    second: "met",
    third: "met",
    geo: "შეხვედრა",
  },
  {
    first: "melt",
    second: "melted",
    third: "molten",
    geo: "დნობა",
  },
  {
    first: "mow",
    second: "mowed",
    third: "mown",
    geo: "თიბვა",
  },
  {
    first: "pay",
    second: "paid",
    third: "paid",
    geo: "გადახდა",
  },
  {
    first: "prove",
    second: "proved",
    third: "proven",
    geo: "დამტკიცება",
  },
  {
    first: "put",
    second: "put",
    third: "put",
    geo: "დადება",
  },
  {
    first: "read",
    second: "read",
    third: "read",
    geo: "წაკითხვა",
  },
  {
    first: "ride",
    second: "rode",
    third: "ridden",
    geo: "ტარება (ცხენის)",
  },
  {
    first: "ring",
    second: "rang",
    third: "rung",
    geo: "დარეკვა",
  },
  {
    first: "rise",
    second: "rose",
    third: "risen",
    geo: "აწევა",
  },
  {
    first: "run",
    second: "ran",
    third: "run",
    geo: "სირბილი",
  },
  {
    first: "say",
    second: "said",
    third: "said",
    geo: "თქმა",
  },
  {
    first: "see",
    second: "saw",
    third: "seen",
    geo: "ხედვა",
  },
  {
    first: "seek",
    second: "sought",
    third: "sought",
    geo: "ძიება",
  },
  {
    first: "sell",
    second: "sold",
    third: "sold",
    geo: "გაყიდვა",
  },
  {
    first: "send",
    second: "sent",
    third: "sent",
    geo: "გაგზავნა",
  },
  {
    first: "set",
    second: "set",
    third: "set",
    geo: "დაყენება",
  },
  {
    first: "shake",
    second: "shook",
    third: "shaken",
    geo: "შენჯღრევა",
  },
  {
    first: "shed",
    second: "shed",
    third: "shed",
    geo: "მოშორება",
  },
  {
    first: "shine",
    second: "shone",
    third: "shone",
    geo: "ნათება",
  },
  {
    first: "shoot",
    second: "shot",
    third: "shot",
    geo: "სროლა",
  },
  {
    first: "show",
    second: "showed",
    third: "shown",
    geo: "ჩვენება",
  },
  {
    first: "shrink",
    second: "shrank",
    third: "shrunk",
    geo: "შემცირება",
  },
  {
    first: "shut",
    second: "shut",
    third: "shut",
    geo: "დახურვა",
  },
  {
    first: "sing",
    second: "sang",
    third: "sung",
    geo: "სიმღერა",
  },
  {
    first: "sink",
    second: "sank",
    third: "sunk",
    geo: "ჩაძირვა",
  },
  {
    first: "sit",
    second: "sat",
    third: "sat",
    geo: "ჯდომა",
  },
  {
    first: "slay",
    second: "slew",
    third: "slain",
    geo: "მოკვლა",
  },
  {
    first: "sleep",
    second: "slept",
    third: "slept",
    geo: "ძილი",
  },
  {
    first: "slide",
    second: "slid",
    third: "slid",
    geo: "სრიალი",
  },
  {
    first: "sling",
    second: "slung",
    third: "slung",
    geo: "ტყორცნა",
  },
  {
    first: "slink",
    second: "slunk",
    third: "slunk",
    geo: "მიპარვა",
  },
  {
    first: "slit",
    second: "slit",
    third: "slit",
    geo: "გაჭრა",
  },
  {
    first: "smite",
    second: "smote",
    third: "smitten",
    geo: "დარტყმა",
  },
  {
    first: "sow",
    second: "sowed",
    third: "sown",
    geo: "დათესვა",
  },
  {
    first: "speak",
    second: "spoke",
    third: "spoken",
    geo: "საუბარი",
  },
  {
    first: "spend",
    second: "spent",
    third: "spent",
    geo: "დახარჯვა",
  },
  {
    first: "spill",
    second: "spilt",
    third: "spilt",
    geo: "დაღვრა",
  },
  {
    first: "spin",
    second: "spun",
    third: "spun",
    geo: "დატრიალება",
  },
  {
    first: "spit",
    second: "spat",
    third: "spat",
    geo: "გადაფურთხება",
  },
  {
    first: "split",
    second: "split",
    third: "split",
    geo: "დანაწილება",
  },
  {
    first: "spread",
    second: "spread",
    third: "spread",
    geo: "გავრცელება",
  },
  {
    first: "spring",
    second: "sprang",
    third: "sprung",
    geo: "ხტუნვა",
  },
  {
    first: "stand",
    second: "stood",
    third: "stood",
    geo: "დგომა",
  },
  {
    first: "steal",
    second: "stole",
    third: "stolen",
    geo: "მოპარვა",
  },
  {
    first: "stick",
    second: "stuck",
    third: "stuck",
    geo: "დაწებება",
  },
  {
    first: "sting",
    second: "stung",
    third: "stung",
    geo: "სუსხვა",
  },
  {
    first: "stink",
    second: "stank",
    third: "stunk",
    geo: "ყროლა (ყარს)",
  },
  {
    first: "stride",
    second: "strode",
    third: "stridden",
    geo: "ბიჯება",
  },
  {
    first: "strike",
    second: "struck",
    third: "struck",
    geo: "დარტყმა",
  },
  {
    first: "string",
    second: "strung",
    third: "strung",
    geo: "შეკვრა",
  },
  {
    first: "strive",
    second: "strove",
    third: "striven",
    geo: "მისწრაფება",
  },
  {
    first: "swear",
    second: "swore",
    third: "sworn",
    geo: "დაფიცება",
  },
  {
    first: "sweep",
    second: "swept",
    third: "swept",
    geo: "გამოგვა",
  },
  {
    first: "swell",
    second: "swelled",
    third: "swollen",
    geo: "გასიება",
  },
  {
    first: "swim",
    second: "swam",
    third: "swum",
    geo: "ცურვა",
  },
  {
    first: "swing",
    second: "swung",
    third: "swung",
    geo: "რხევა",
  },
  {
    first: "take",
    second: "took",
    third: "taken",
    geo: "აღება",
  },
  {
    first: "teach",
    second: "taught",
    third: "taught",
    geo: "სწავლება",
  },
  {
    first: "tear",
    second: "tore",
    third: "torn",
    geo: "გაგლეჯა",
  },
  {
    first: "tell",
    second: "told",
    third: "told",
    geo: "თქმა",
  },
  {
    first: "think",
    second: "thought",
    third: "thought",
    geo: "ფიქრი",
  },
  {
    first: "throw",
    second: "threw",
    third: "thrown",
    geo: "გადაგდება",
  },
  {
    first: "thrust",
    second: "thrust",
    third: "thrust",
    geo: "ჩარჭობა",
  },
  {
    first: "tread",
    second: "trod",
    third: "trodden",
    geo: "ბიჯება",
  },
  {
    first: "understand",
    second: "understood",
    third: "understood",
    geo: "გაგება",
  },
  {
    first: "wake",
    second: "woke",
    third: "woken",
    geo: "გაღვიძება",
  },
  {
    first: "wear",
    second: "wore",
    third: "worn",
    geo: "ტარება (ტანსაცმლის)",
  },
  {
    first: "weave",
    second: "wove",
    third: "woven",
    geo: "ქსოვა",
  },
  {
    first: "weep",
    second: "wept",
    third: "wept",
    geo: "ტირილი",
  },
  {
    first: "win",
    second: "won",
    third: "won",
    geo: "მოგება",
  },
  {
    first: "wind",
    second: "wound",
    third: "wound",
    geo: "ხვევა",
  },
  {
    first: "wring",
    second: "wrung",
    third: "wrung",
    geo: "დაგრეხა",
  },
  {
    first: "write",
    second: "wrote",
    third: "written",
    geo: "წერა",
  },
];
